tasks:
  - name: terraform
    before: |
      source ./bin/Terraform_install_cli.sh
      source ./bin/Set_tf_alias.sh
      source ./bin/Generate_TF_Credentials.sh
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/AWS_install_cli.sh
      source ./bin/Set_tf_alias.sh
      source ./bin/Generate_TF_Credentials.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform